<?php

declare(strict_types=1);

namespace Drupal\ai_whatsapp_automation\Application\Webhook;

use Drupal\ai_whatsapp_automation\Application\Evolution\QRProvider;
use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Logger\LoggerChannelFactoryInterface;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\GuzzleException;
use Psr\Log\LoggerInterface;

/**
 * Sends provider responses generated by the conversation engine.
 */
final class ProviderMessageSenderService {

  /**
   * The logger channel.
   */
  private readonly LoggerInterface $logger;

  /**
   * Constructs a ProviderMessageSenderService object.
   */
  public function __construct(
    private readonly ClientInterface $httpClient,
    private readonly ConfigFactoryInterface $configFactory,
    LoggerChannelFactoryInterface $loggerFactory,
    private readonly QRProvider $qrProvider,
  ) {
    $this->logger = $loggerFactory->get('ai_whatsapp_automation');
  }

  /**
   * Sends a text response through the originating provider.
   *
   * @param array<string, mixed> $message
   *   Normalized incoming message data.
   *
   * @return array<string, mixed>
   *   Delivery result.
   */
  public function sendText(string $provider, array $message, string $text): array {
    $text = trim($text);
    if ($text === '') {
      return ['status' => 'skipped_empty_response'];
    }

    return match ($provider) {
      'twilio' => $this->sendTwilio($message, $text),
      'cloud_api' => $this->sendCloudApi($message, $text),
      'evolution' => $this->sendEvolution($message, $text),
      default => ['status' => 'unsupported_provider'],
    };
  }

  /**
   * Sends a Twilio WhatsApp message.
   *
   * @param array<string, mixed> $message
   *   Normalized incoming message data.
   */
  private function sendTwilio(array $message, string $text): array {
    $config = $this->configFactory->get('ai_whatsapp_automation.settings');
    $account_sid = (string) $config->get('twilio.account_sid');
    $auth_token = (string) $config->get('twilio.auth_token');
    $from = $this->resolveTwilioFrom($message);
    $to = (string) ($message['phone'] ?? '');

    if ($account_sid === '' || $auth_token === '' || $from === '' || $to === '') {
      return ['status' => 'skipped_missing_configuration'];
    }

    $twilio_from = $this->prefixWhatsApp($from);
    $twilio_to = $this->prefixWhatsApp($to);

    return $this->request('POST', 'https://api.twilio.com/2010-04-01/Accounts/' . $account_sid . '/Messages.json', [
      'auth' => [$account_sid, $auth_token],
      'form_params' => [
        'From' => $twilio_from,
        'To' => $twilio_to,
        'Body' => $text,
      ],
      'ai_whatsapp_context' => [
        'provider' => 'twilio',
        'from' => $twilio_from,
        'to' => $twilio_to,
      ],
    ]);
  }

  /**
   * Resolves the Twilio WhatsApp sender for a message.
   *
   * Account-specific phone numbers support multi-number routing. The global
   * setting remains a fallback for legacy single-number installations.
   *
   * @param array<string, mixed> $message
   *   Normalized incoming message data.
   */
  private function resolveTwilioFrom(array $message): string {
    $account_phone = trim((string) ($message['account_phone'] ?? ''));
    if ($account_phone !== '') {
      return $account_phone;
    }

    return (string) $this->configFactory
      ->get('ai_whatsapp_automation.settings')
      ->get('twilio.whatsapp_number');
  }

  /**
   * Sends a WhatsApp Cloud API message.
   *
   * @param array<string, mixed> $message
   *   Normalized incoming message data.
   */
  private function sendCloudApi(array $message, string $text): array {
    $config = $this->configFactory->get('ai_whatsapp_automation.settings');
    $access_token = (string) $config->get('whatsapp_cloud.access_token');
    $phone_number_id = (string) $config->get('whatsapp_cloud.phone_number_id');
    $to = (string) ($message['phone'] ?? '');

    if ($access_token === '' || $phone_number_id === '' || $to === '') {
      return ['status' => 'skipped_missing_configuration'];
    }

    return $this->request('POST', 'https://graph.facebook.com/v20.0/' . $phone_number_id . '/messages', [
      'headers' => [
        'Authorization' => 'Bearer ' . $access_token,
        'Content-Type' => 'application/json',
      ],
      'json' => [
        'messaging_product' => 'whatsapp',
        'to' => ltrim($to, '+'),
        'type' => 'text',
        'text' => [
          'preview_url' => FALSE,
          'body' => $text,
        ],
      ],
    ]);
  }

  /**
   * Sends an Evolution API message.
   *
   * @param array<string, mixed> $message
   *   Normalized incoming message data.
   */
  private function sendEvolution(array $message, string $text): array {
    $config = $this->configFactory->get('ai_whatsapp_automation.settings');
    $instance = (string) ($message['account_phone'] ?? '');
    if ($instance === '') {
      $instance = (string) $config->get('evolution.instance_name');
    }
    $to = (string) ($message['phone'] ?? '');

    if ($instance === '' || $to === '') {
      return ['status' => 'skipped_missing_configuration'];
    }

    $result = $this->qrProvider->sendMessage($instance, $to, $text);

    if (($result['success'] ?? FALSE) !== TRUE) {
      return [
        'status' => 'failed',
        'error' => (string) ($result['error'] ?? $result['status'] ?? 'Evolution API send failed.'),
      ];
    }

    return [
      'status' => 'sent',
      'status_code' => $result['status_code'] ?? NULL,
      'body' => json_encode($result['data'] ?? [], JSON_THROW_ON_ERROR),
    ];
  }

  /**
   * Performs an HTTP request and normalizes the result.
   *
   * @param array<string, mixed> $options
   *   Guzzle request options.
   *
   * @return array<string, mixed>
   *   Normalized delivery result.
   */
  private function request(string $method, string $url, array $options): array {
    $context = is_array($options['ai_whatsapp_context'] ?? NULL)
      ? $options['ai_whatsapp_context']
      : [];
    unset($options['ai_whatsapp_context']);

    try {
      $response = $this->httpClient->request($method, $url, $options + ['timeout' => 15]);
    }
    catch (GuzzleException $exception) {
      $this->logger->error('Provider message send failed from @from to @to: @message', [
        '@from' => (string) ($context['from'] ?? ''),
        '@to' => (string) ($context['to'] ?? ''),
        '@message' => $exception->getMessage(),
      ]);

      return [
        'status' => 'failed',
        'error' => $exception->getMessage(),
      ];
    }

    return [
      'status' => 'sent',
      'status_code' => $response->getStatusCode(),
      'body' => (string) $response->getBody(),
      'from' => (string) ($context['from'] ?? ''),
      'to' => (string) ($context['to'] ?? ''),
    ];
  }

  /**
   * Ensures a Twilio WhatsApp address has the expected prefix.
   */
  private function prefixWhatsApp(string $phone): string {
    $phone = trim($phone);

    return str_starts_with($phone, 'whatsapp:') ? $phone : 'whatsapp:' . $phone;
  }

}
